config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :documents

  authenticated :user do
    root "documents#index", as: "authenticated_root"
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :documents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :find_document, only: [:show, :edit, :update, :destroy]

  def index
    @documents = Document.where(user_id: current_user).order("created_at DESC")
  end

  def show
  end

  def new
    @document = current_user.documents.build
  end

  def create
    @document = current_user.documents.build(document_params)
    if @document.save
      render 'show'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if document.update(document_params)
      redirect_to @doc
    else
      render 'edit'
    end
  end

  def destroy
    @document.destroy
    redirect_to documents_path
  end

  private

  def find_document
    @document = Document.find(params[:id])
  end

  def document_params
    params.require(:document).permit(:title, :content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/documents/_form.html.erb
<%= simple_form_for @document do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.button :submit %>
<% end %>

app/views/documents/edit.html.erb
<h1>Edit Document</h1>
<%= render 'form' %>
<%= link_to "Cancel", document_path %>

app/views/documents/index.html.erb
<div class="wrapper_with_padding">
  <div id="docs">
    <div class="clearfix">
      <% unless @documents.blank? %>
        <% @documents.each do |document|%>
        <span class="doc">
          <a class="" href= <%= url_for(document) %>>
            <p class="title"> <%= document.title %> </p>
            <p class="date"> <%= time_ago_in_words(document.created_at)%> </p>
            <p class="content"> <%= truncate(document.content, length: 20)%></p>
          </a>
        </span>
        <% end %>
        <% else  %>
        <h2>Create Documents</h2>
        <p>Start creating documents and organize your Horcruxes</p>
      <% end %>
    </div>
  </div>
</div>

app/views/documents/new.html.erb
<h1>This is a New View</h1>

<%= render 'form' %>

app/views/documents/show.html.erb
<div class="wrapper_with_padding">
  <div id="doc_show">
      <br />
      <h1 class="title"> <%= @document.title %> </h1>
      <p> <%= @document.content %> </p>
  </div>
</div>
<%= link_to "All Documents", documents_path %>
<%= link_to "Edit Document", edit_document_path(@document) %>
<%= link_to "Trash Document",
            document_path(@document), method: :delete,
            data: { confirm: "Are you sure you want to delete this document?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileCabinet | All About Horcruxes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header_inner">
        <h1> <%= link_to "FileCabinet", root_path %>
          <nav>
            <% if user_signed_in?  %>
              <%= link_to "Create New Document", new_document_path %>
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
            <% else %>
              <%= link_to "Log In", new_user_session_path %>
            <% end %>
          </nav>
        </h1>
      </div>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div id="banner">
  <div class="banner_content">
    <h1> File Cabinet </h1>
      <p>All About Horcruxes. Organized, always. </p>
      <a href="users/sign_up" class="button"> Enter </a>
    </div>
  </div>

  <div id="callouts">
    <div class="callout_inner">
      <div class='wrapper'>
        <div class="callout">
          <h2>Organize</h2>
          <p>
          Organize your life! Or else. Shantay you stay everyone else
          sashay away. Rings, goblets, journals oh my.
          </p>
        </div>
      </div>
    </div>
  </div>

  <div id="bottom_cta">
    <div>
      <h2>Go Ahead!</h2>
      <br/>
      <a href="users/sign_up" class="button"> Join Now </a>
    </div>
  </div>